ARG ARCH=frommakefile
ARG DOCKERSRC=frommakefile
ARG USERNAME=frommakefile
#
FROM ${USERNAME}/${DOCKERSRC}:${ARCH}
#
ARG PUID=1000
ARG PGID=1000
ARG ROLE=master
#
ENV DGID=995 \
    WORKERNAME= \
    PASSWORD= \
    MASTERADDRESS= \
    REQUIRED_PIP= \
    REQUIRED_APK=
#
RUN set -xe \
    && addgroup -g ${DGID} docker && addgroup alpine docker \
    && apk add -uU --virtual .build-dependencies python3-dev libffi-dev openssl-dev build-base \
    && if [ "${ROLE}" = "master" ]; \
    then \
        pip install --no-cache --upgrade buildbot[bundle,tls] txrequests ; \
    fi \
    && if [ "${ROLE}" = "worker" ]; \
    then \
        pip install --no-cache --upgrade buildbot-worker ; \
    fi \
    && apk del --purge .build-dependencies \
    && rm -rf /var/cache/apk/* /tmp/*

COPY root/ /

VOLUME /home/alpine

EXPOSE 9989 8010/tcp 9990

ENTRYPOINT ["/init"]
