#!/usr/bin/with-contenv bash

# cd /home/alpine/buildbot-config || exit 1;
# s6-setuidgid alpine buildbot start --nodaemon ${WORKERNAME}-master;

cd /home/alpine/buildbot-config/${WORKERNAME}-master || exit 1;
s6-setuidgid alpine twistd --nodaemon --no_save -y ./buildbot.tac;
